spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: true
  datasource:
    url: jdbc:mysql://localhost:3306/inssaDB?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Ckddud0828?
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        use_sql_comments: true
        jdbc:
          time_zone: UTC


jwt:
  secret-key: awhekdnsckddud0828awhekdnsckddud0828awhekdnsckddud0828
  expiration: 3600000

file:
  path: src/main/resources/static/files/